Lazy
AnnaKasatkina/SecondCourse pull request #2
Opened 2024-09-24 17:25 UTC by AnnaKasatkina

2024-11-30 20:09 UTC, yurii-litvinov requested changes

2024-11-30 20:09 UTC, yurii-litvinov commented on ThirdSemester/Lazy/LazeTests/LazyTests.cs
> +        }, isThreadSafe);
Что-то тут отступы какие-то противоестественные

2024-11-30 20:09 UTC, yurii-litvinov commented on ThirdSemester/Lazy/LazeTests/LazyTests.cs
> +    }
```suggestion
        => Assert.Throws<ArgumentNullException>(() => CreateLazy<int>(null, isThreadSafe));
```

2024-11-30 20:09 UTC, yurii-litvinov commented on ThirdSemester/Lazy/LazeTests/LazyTests.cs
> +        }
Это через тернарный оператор легко переписать в одну строчку.

2024-11-30 20:09 UTC, yurii-litvinov commented on ThirdSemester/Lazy/Lazy/ILazy.cs
> +public interface ILazy<T>
```suggestion
public interface ILazy<out T>
```
Если можно указать вариантность, лучше указать, это упростит пользование контейнером.

2024-11-30 20:09 UTC, yurii-litvinov commented on ThirdSemester/Lazy/Lazy/SimpleLazy.cs
> +    }
```suggestion
    public SimpleLazy(Func<T> supplier)
        => this.supplier = supplier ?? throw new ArgumentNullException(nameof(supplier));
```

2024-11-30 20:09 UTC, yurii-litvinov commented on ThirdSemester/Lazy/Lazy/ThreadSafeLazy.cs
> +            return this.value!;
Условие явно разрешает value быть null, так что можно было Get сделать возвращающим `T?`

2024-11-30 20:09 UTC, yurii-litvinov commented on ThirdSemester/Lazy/Lazy/ThreadSafeLazy.cs
> +                this.isEvaluated = true;
isEvaluated должен быть volatile, иначе может так случиться, что `this.isEvaluated = true` на 45-й строчке другой поток увидит раньше, чем `this.value = this.supplier();`

2024-12-12 18:07 UTC, AnnaKasatkina commented on ThirdSemester/Lazy/LazeTests/LazyTests.cs
> +        }, isThreadSafe);
TextGuide исправляет на такое форматирование и ругается на другие варианты ¯\_(ツ)_/¯

2024-12-25 22:03 UTC, yurii-litvinov approved these changes
Комментарий к коммиту не очень, bags — это "мешки". Но окей, достаточно хорошо, зачтена

2024-12-25 22:03 UTC, yurii-litvinov commented on ThirdSemester/Lazy/Lazy/SimpleLazy.cs
> +        return this.value!;
Так supplier может вернуть null и тут странно упадёт. Стоило явно проверять или не делать T не nullable

2024-12-26 07:17 UTC, merged